name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: wire2c7/workflows/.github/workflows/nix-ci.yaml@3c49686fb929d3427e0abad5a4ed214defb0b903 # v1.0.0
